# Generated by Django 4.1.7 on 2023-03-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zombie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('strength', models.IntegerField()),
                ('weakness', models.CharField(max_length=255)),
                ('attack_plan', models.TextField()),
            ],
        ),
    ]
