# Generated by Django 4.1.7 on 2023-03-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombie_app', '0002_zombie_antidote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZombieAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('zombies', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('attacks', models.ManyToManyField(blank=True, to='zombie_app.zombieattack')),
            ],
        ),
    ]
