# Generated by Django 4.1.7 on 2023-03-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombie_app', '0004_remove_zombieattack_attacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zombie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zombieattack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
