# Generated by Django 4.1.7 on 2023-03-29 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombie_app', '0005_alter_zombie_id_alter_zombieattack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zombie',
            name='strength',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
